/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SCP-173 (https://sketchfab.com/username_Unknown)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/battery-cccf3dcca7be4365b22ff59433024586
Title: Battery
*/

import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { Float, useGLTF } from '@react-three/drei'

export default function Battery(props) {
    // Load geometry/materials from battery.glb
    const { nodes, materials } = useGLTF('models/battery.glb')

    // Create a ref for the group we want to rotate
    const batteryRef = useRef()

    // Use the useFrame hook to rotate it a bit every frame
    useFrame((state, delta) => {
        if (batteryRef.current) {
            // Rotate around the Y axis (vertical) by 0.5 radians per second, for example
            batteryRef.current.rotation.y += 0.5 * delta
        }
    })

    return (
        <group ref={batteryRef} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={15}>
                <mesh
                    geometry={nodes.Object_2.geometry}
                    material={materials['Material.001']}
                />
                <mesh
                    geometry={nodes.Object_3.geometry}
                    material={materials['Material.002']}
                />
                <mesh
                    geometry={nodes.Object_4.geometry}
                    material={materials.None}
                />
            </group>
        </group>
    )
}

// Preload the GLB so it's cached
useGLTF.preload('models/battery.glb')
