/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DAVID 3D ART (https://sketchfab.com/david3dart)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/potato-glados-from-portal-2-a81175115d544237a19070c582882f02
Title: Potato GLADOS - From Portal 2
*/

import { Float, useGLTF } from '@react-three/drei'

const Glados = (props) => {
    // Load the .glb model
    const { nodes, materials } = useGLTF('models/glados.glb')

    return (
        <Float floatIntensity={0}>
            <group scale={0.4} {...props} dispose={null}>
                {/* The group transformations are from the original snippet */}
                <group rotation={[-2.5, 6, 9]} position={[-15, -3, 0]} scale={0.7}>
                    <mesh
                        geometry={nodes.Potato_Glados_Texture_0_0.geometry}
                        material={materials.Texture_0}
                    />
                    <mesh
                        geometry={nodes.Potato_Glados_Mat_1.geometry}
                        material={materials.material}
                        position={[0, 0.079, 0.181]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[0.392, 0.392, 0.527]}
                    />
                </group>
            </group>
        </Float>
    )
}

useGLTF.preload('models/glados.glb')

export default Glados;
