// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: Michael Klement (https://sketchfab.com/mklement)
// License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
// Source: https://sketchfab.com/3d-models/companion-cube-47502a51b211475b9750b04b4b1dffc4
// Title: Companion Cube
// */
//
// import gsap from 'gsap';
// import { useGSAP } from '@gsap/react';
// import { useRef, useState } from 'react';
// import { Float, useGLTF, useTexture } from '@react-three/drei';
//
//
// const PortalCube = ({ ...props }) => {
//     const { nodes, materials } = useGLTF('/models/companion-cube.glb');
//
//     const texture = useTexture('textures/DefaultMaterial_baseColor.jpeg');
//
//     const cubeRef = useRef();
//     const [hovered, setHovered] = useState(false);
//
//     useGSAP(() => {
//         gsap
//             .timeline({
//                     repeat: -1,
//                     repeatDelay: 0.5,
//                 })
//             .to(cubeRef.current.rotation, {
//                 y: hovered ? '+=2' : `+=${Math.PI * 2}`,
//                 x: hovered ? '+=2' : `-=${Math.PI * 2}`,
//                 duration: 2.5,
//                 stagger: {
//                     each: 0.15,
//                 },
//             });
//     });
//
//     return (
//         <Float floatIntensity={2}>
//             <group {...props} dispose={null}>
//                 <group rotation={[-Math.PI / 2, 0, 0]}>
//                     <group
//                         ref={cubeRef}
//                         onPointerEnter={() => setHovered(true)}
//                         onPointerLeave={() => setHovered(false)}
//                         rotation={[Math.PI / 2, 0, 0]}
//                     >
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_1.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_2.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_3.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_4.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_5.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_6.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_7.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_8.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_9.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_10.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_11.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_12.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_13.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_14.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_15.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_16.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_17.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_18.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_19.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_20.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_21.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_22.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_23.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_24.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_25.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_26.geometry}
//                               material={materials.DefaultMaterial}/>
//                         <meshMatcapMaterial matcap={texture} toneMapped={false}/>
//                     </group>
//                 </group>
//             </group>
//         </Float>
//     );
// }
//
// useGLTF.preload('/models/companion-cube.glb');
//
// export default PortalCube;