/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ArbitraryCanary (https://sketchfab.com/ArbitraryCanary)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/k-vrc-love-death-robots-1a89dbad3a894642958405728ba66d9d
Title: K-VRC | Love, Death + Robots
*/

import { Float, useGLTF } from '@react-three/drei';

const RobotMain = (props) => {
    const { nodes, materials } = useGLTF('models/robot-main.glb')
    return (
        <Float floatIntensity={0}>
            <group {...props} dispose={null}>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_2.geometry}
                        material={materials.BlackMetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_3.geometry}
                        material={materials.ButterflyBody}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_4.geometry}
                        material={materials.ButterflyWings}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_5.geometry}
                        material={materials.Glow}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_6.geometry}
                        material={materials.OrangePaint}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_7.geometry}
                        material={materials.Screen}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_8.geometry}
                        material={materials.Stripes}
                    />
                </group>
            </group>
        </Float>
    )
}

useGLTF.preload('models/robot-main.glb')

export default RobotMain;
